#Create a list
l1 = [1,3,4,5]

#Sort the list in place ascending
l1.sort(reverse=False)
print(l1)

#Sort the list in place descending
l1.sort(reverse=True)
print(l1)

#Create a new list while sorting
l2 = sorted(l1, reverse=False)
print(l2)

#print the list in the remainder generated by %2
l2 = sorted(l1, reverse=False, key=lambda v1:v1%2)
print(l2)

#print the list in the order if the number leaves a remainder or not, all false go before as false is 0, true is 1generated by %2
l2 = sorted(l1, reverse=False, key=lambda v1:v1%2==0)
print(l2)

'''
l1=[1, 3, 2, 4, 2, 1]
l2=[3, 1, 1, 4, 2, 2]
'''
